name: CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: npm ci
      - name: Run tests (fixtures)
        run: npm test
      - name: Validate schemas
        run: npm run validate:all

  package_vscode:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install vsce
        run: npm install --global @vscode/vsce
      - name: Package VS Code extension
        working-directory: editors/vscode
        env:
          VSIX_NAME: drrx-${{ github.ref_name }}.vsix
        run: vsce package --out "$VSIX_NAME"
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: DrRx ${{ github.ref_name }}
          draft: false
          prerelease: false
      - name: Upload VSIX asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: editors/vscode/drrx-${{ github.ref_name }}.vsix
          asset_name: drrx-${{ github.ref_name }}.vsix
          asset_content_type: application/octet-stream
